version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # 개발 모드에서 볼륨 마운트 (필요시)
    # volumes:
    #   - ./src:/app/src:ro 